# Docs: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "automerge"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "automerge"
  - package-ecosystem: "pip"
    directory: "/.jb"
    schedule:
      interval: "weekly"
    labels:
      - "automerge"
