version: 2
updates:
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/.github"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    open-pull-requests-limit: 0
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    open-pull-requests-limit: 0

