[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MarkdownTables = "1862ce21-31c7-451e-824c-f20fa3f90fa2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ComponentArrays = "0.15.31"
DataInterpolations = "8.9.0"
DiffEqCallbacks = "4.12.0"
JumpProcesses = "9.19.3"
OrdinaryDiffEq = "6.105.0"
Peaks = "0.6.0"
SHA = "0.7.0"
Statistics = "1.11.1"
StatsBase = "0.34.9"
SteadyStateDiffEq = "2.9.0"
