# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: ../_site

# https://quarto.org/docs/websites/
website:
  title: Quarto Julia Template
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/ntumitolab/mmsb-bebi-5009
  site-url: https://ntumitolab.github.io/mmsb-bebi-5009
  # https://quarto.org/docs/websites/website-navigation.html
  sidebar:
    style: "docked"
    search: true
    contents: auto
    tools:
      - icon: github
        href: https://github.com/ntumitolab/mmsb-bebi-5009

# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly
    # css: styles.css

# Default options
# notebook-links: true

# Execution
execute:
  cache: true
engines: ['julia']
