name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - name: "Run CompatHelper"
        run: |
          import Pkg
          ENV["JULIA_PKG_SERVER"] = ""
          Pkg.Registry.add("General")
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "3"
          Pkg.add(; name, uuid, version)
          import CompatHelper
          CompatHelper.main()
        shell: julia --color=yes --threads=auto {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
          # COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}