name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every week

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sosiristseng/docker-juliabook:1.8.0rc3
      env:
        JULIA_PKG_PRECOMPILE_AUTO: 0
        JULIA_NUM_THREADS: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Julia dependencies
        run: julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          labels: |
            automerge
