name: Auto update Julia dependencies

env:
  JULIA_VERSION: "1.7"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every week

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Julia ${{ env.JULIA_VERSION }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VERSION }}
      - name: Update Julia dependencies
        run: julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: |
            automerge
